name: 'Create ECR Repo'
description: 'A GitHub Action for creating AWS ECR repositories if they don''t already exist'
inputs:
  DOCKER_REPO_NAME:
    description: 'The ECR repository name'
    required: true
  NUM_DAYS_BEFORE_EXPIRING_UNTAGGED_IMAGES:
    description: 'The number of days after which untagged images will expire'
    required: false
    default: '31'

  # These next two go together to create the "Expire old images as new ones are built" lifecycle policy
  TAG_PREFIX:
    description: 'The image tag prefix used so that we can expire old images as new ones are built'
    required: false
    default: 'sha-'
  NUM_TAGGED_IMAGES_TO_RETAIN:
    description: 'The number of images with the given prefix to retain'
    required: false
    default: '10'
    # Defaults to keep latest 10 images tagged sha-
runs:
  using: 'node12'
  main: 'dist/index.js'